# Generated by Django 5.1.1 on 2024-10-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relecloud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cruise',
            name='end_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='cruise',
            name='start_date',
            field=models.DateField(default=None),
        ),
    ]
